name: Deploy Web

on:
  push:
    branches: [main]
    paths:
      - "apps/web/**"
      - "packages/shared/**"

  workflow_dispatch: # Manual trigger

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Trigger Vercel Deploy Hook
        run: curl -s -X POST "${{ secrets.VERCEL_DEPLOY_HOOK }}"
